webprojem-villasec/YeniOdev/Controllers/BolgeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YeniOdev.Data;
using YeniOdev.Models;

namespace YeniOdev.Controllers
{
    public class BolgeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BolgeController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Bolge
        public async Task<IActionResult> Index()
        {
            return View(await _context.Bolge.ToListAsync());
        }

        // GET: Bolge/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bolge = await _context.Bolge
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bolge == null)
            {
                return NotFound();
            }

            return View(bolge);
        }

        // GET: Bolge/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Bolge/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BolgeAd")] Bolge bolge)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bolge);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bolge);
        }

        // GET: Bolge/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bolge = await _context.Bolge.FindAsync(id);
            if (bolge == null)
            {
                return NotFound();
            }
            return View(bolge);
        }

        // POST: Bolge/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BolgeAd")] Bolge bolge)
        {
            if (id != bolge.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bolge);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BolgeExists(bolge.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bolge);
        }

        // GET: Bolge/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bolge = await _context.Bolge
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bolge == null)
            {
                return NotFound();
            }

            return View(bolge);
        }

        // POST: Bolge/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bolge = await _context.Bolge.FindAsync(id);
            _context.Bolge.Remove(bolge);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BolgeExists(int id)
        {
            return _context.Bolge.Any(e => e.Id == id);
        }
    }
}

webprojem-villasec/YeniOdev/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YeniOdev.Data;
using YeniOdev.Models;

namespace YeniOdev.Controllers
{
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UserController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.User.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Ad,Soyad,Adres,Telefon,DogumTarihi,Cinsiyet,Sehir")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Ad,Soyad,Adres,Telefon,DogumTarihi,Cinsiyet,Sehir")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.User.FindAsync(id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.Id == id);
        }
    }
}

webprojem-villasec/YeniOdev/Controllers/VillaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YeniOdev.Data;
using YeniOdev.Models;

namespace YeniOdev.Controllers
{
    public class VillaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VillaController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Villas

        public IActionResult Detaylar()
        {
            return View();

        }
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Villa.Include(v => v.Adres).Include(v => v.Bolge).Include(v => v.Kategori);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Villas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var villa = await _context.Villa
                .Include(v => v.Adres)
                .Include(v => v.Bolge)
                .Include(v => v.Kategori)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (villa == null)
            {
                return NotFound();
            }

            return View(villa);
        }

        // GET: Villas/Create
        public IActionResult Create()
        {
            ViewData["AdresId"] = new SelectList(_context.Adres, "Id", "Id");
            ViewData["BolgeId"] = new SelectList(_context.Bolge, "Id", "Id");
            ViewData["KategoriId"] = new SelectList(_context.Kategori, "Id", "Id");
            return View();
        }

        // POST: Villas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,VillaAd,KategoriId,AdresId,BolgeId,Fiyat,Metrekare,Kapasite,Fotograf,Aciklama")] Villa villa)
        {
            if (ModelState.IsValid)
            {
                _context.Add(villa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AdresId"] = new SelectList(_context.Adres, "Id", "Id", villa.AdresId);
            ViewData["BolgeId"] = new SelectList(_context.Bolge, "Id", "Id", villa.BolgeId);
            ViewData["KategoriId"] = new SelectList(_context.Kategori, "Id", "Id", villa.KategoriId);
            return View(villa);
        }

        // GET: Villas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var villa = await _context.Villa.FindAsync(id);
            if (villa == null)
            {
                return NotFound();
            }
            ViewData["AdresId"] = new SelectList(_context.Adres, "Id", "Id", villa.AdresId);
            ViewData["BolgeId"] = new SelectList(_context.Bolge, "Id", "Id", villa.BolgeId);
            ViewData["KategoriId"] = new SelectList(_context.Kategori, "Id", "Id", villa.KategoriId);
            return View(villa);
        }

        // POST: Villas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,VillaAd,KategoriId,AdresId,BolgeId,Fiyat,Metrekare,Kapasite,Fotograf,Aciklama")] Villa villa)
        {
            if (id != villa.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(villa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VillaExists(villa.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AdresId"] = new SelectList(_context.Adres, "Id", "Id", villa.AdresId);
            ViewData["BolgeId"] = new SelectList(_context.Bolge, "Id", "Id", villa.BolgeId);
            ViewData["KategoriId"] = new SelectList(_context.Kategori, "Id", "Id", villa.KategoriId);
            return View(villa);
        }

        // GET: Villas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var villa = await _context.Villa
                .Include(v => v.Adres)
                .Include(v => v.Bolge)
                .Include(v => v.Kategori)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (villa == null)
            {
                return NotFound();
            }

            return View(villa);
        }

        // POST: Villas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var villa = await _context.Villa.FindAsync(id);
            _context.Villa.Remove(villa);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VillaExists(int id)
        {
            return _context.Villa.Any(e => e.Id == id);
        }
    }
}

webprojem-villasec/YeniOdev/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VillaSeç</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/styles.css" rel="stylesheet" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container px-5">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VillaSeç</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />

                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    </ul>

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Admin
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                                <a class="dropdown-item" asp-area="" asp-controller="Kategori" asp-action="Index">Kategoriler</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Villa" asp-action="Index">Villalar</a>
                                <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Index">Kullanıcılar</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Bolge" asp-action="Index">Bolgeler</a>
                            </div>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-column-reverse">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Bölgeler
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                                <a class="dropdown-item" asp-area="Bolge" asp-controller="" asp-action="Index">Fethiye</a>
                                <a class="dropdown-item" asp-area="Bolge" asp-controller="" asp-action="Index">Kaş</a>
                                <a class="dropdown-item" asp-area="Bolge" asp-controller="" asp-action="Index">Marmaris</a>
                            </div>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-column-reverse">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Kategoriler
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                                <a class="dropdown-item" asp-area="" asp-controller="" asp-action="Index">Ekonomik Villalar</a>
                                <a class="dropdown-item" asp-area="" asp-controller="" asp-action="Index">Lüks Villalar</a>
                                <a class="dropdown-item" asp-area="" asp-controller="" asp-action="Index">Jakuzili Villalar</a>
                            </div>

                        </li>
                    </ul>
                    <ul class="navbar-nav flex-column-reverse">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>

                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - VillaSeç - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false)


</body>

</html>